export const LOADING = "LOADING"

export const GET_COURSE_INPUTS = "GET_COURSE_INPUTS"
export const GET_COURSE_INPUTS_MORE = 'GET_COURSE_INPUTS_MORE'
export const ADD_COURSE_INPUTS_MORE = "ADD_COURSE_INPUTS_MORE"
export const GET_COURSE_CRICULUM = "GET_COURSE_CRICULUM"
export const EDIT_ADD_COURSE = "EDIT_ADD_COURSE"
export const EDIT_CRICCULUM = "EDIT_CRICCULUM"
export const EDIT_LIVE_CLASSES = "EDIT_LIVE_CLASSES"
export const EDIT_PREVIEW = "EDIT_PREVIEW"
export const EDIT_QUIZ = "EDIT_QUIZ"


export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_ADMIN = 'LOGOUT_ADMIN'
export const UPDATE_USER = 'UPDATE_USER'
export const ERROR = 'ERROR';
export const SET_TOKEN = 'SET_TOKEN';
export const REGISTER_SOCIAL_MEDIA = 'REGISTER_SOCIAL_MEDIA'
export const SIGNUP_USER = "SIGNUP_USER"
export const OPT_VERIFY = "OPT_VERIFY"
export const CLEAN_STATE = "CLEAN_STATE"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const FORGOT_PASSWORD_EMAIL = "FORGOT_PASSWORD_EMAIL" 

export const GET_CATAGORY = "GET_CATAGORY"
export const GET_FETAURE = "GET_FETAURE"
export const GET_LATEST = "GET_LATEST"
export const GET_BY_CATAGORY_FEATURE = "GET_BY_CATAGORY_FEATURE"

export const GET_SEARCH_COURSE = 'GET_SEARCH_COURSE'
export const GET_BY_CATAGORY_COURSE = 'GET_BY_CATAGORY_COURSE'

export const GET_BY_CATAGORY = "GET_BY_CATAGORY"

export const GET_FILTER_PRICE = "GET_FILTER_PRICE"


export const GET_ALL_COURSES = "GET_ALL_COURSES"
export const GET_SORTED_COURSE = "GET_SORTED_COURSE"
export const LIVE_COURSE = "LIVE_COURSE"

export const REG_CART = 'REG_CART'
export const GET_CART = 'GET_CART'
export const DELETE_CART = 'DELETE_CART'
export const UPDATE_CART = "UPDATE_CART"

export const REG_BOOK_MARK = "REG_BOOK_MARK"
export const GET_BOOK_MARK = "GET_BOOK_MARK"

export const LOGOUT_INST = "LOGOUT_INST"
export const REG_CHECKOUT_DATA = 'REG_CHECKOUT_DATA'
export const FETCH_CHECKOUT_DATA = 'FETCH_CHECKOUT_DATA'
export const RESET_CART = "RESET_CART"
export const PAYEMENT_CARD = "PAYEMENT_CARD"

export const LOGIN_ADMIN = "LOGIN_ADMIN"
export const GET_ALL_INSTRUCTOR = "GET_ALL_INSTRUCTOR"
export const GET_ALL_STUDENT = "GET_ALL_STUDENT"
export const DELETE_STU = "DELETE_STU"
export const UPDATE_STU = "UPDATE_STU"
export const DELETE_INS = "DELETE_INS"
export const UPDATE_INS = "UPDATE_INS"
export const GET_SORTED_COURSE_SEARCH ="GET_SORTED_COURSE_SEARCH"

// // clear state admin and instructor and company addCourse

// export const CLEAR_ADCOURSE = "CLEAR_ADCOURSE"
// export const CLEAR_CRICCULUM = "CLEAR_CRICCULUM"
// export const CLEAR_QUIZ = "CLEAR_QUIZ"
// export const CLEAR_lIVE = "CLEAR_lIVE"
// export const CLEAR_PREVIEW = "CLEAR_PREVIEW"



// Instructor AddCourse 
export const ADD_COURSE_INPUTS = "ADD_COURSE_INPUTS"
export const ADD_COURSE_CONTENT_MORE = "ADD_COURSE_CONTENT_MORE"
export const ADD_COURSE_CONTENT = "ADD_COURSE_CONTENT"
export const DEL_COURSE_CONTENT = "DEL_COURSE_CONTENT"
export const DELE_CRICULUM_LECTURE_PREVIEW ="DELE_CRICULUM_LECTURE_PREVIEW"
export const COURSE_ID ="COURSE_ID"
export const GET_COURSE_CATAGORIES = "GET_COURSE_CATAGORIES"


// Instructor Criculum 

export const ADD_CRICULUM = "ADD_CRICULUM"
export const ADD_LECTURE = "ADD_LECTURE"
export const ADD_MORE_CRICULUM = "ADD_MORE_CRICULUM"
export const ADD_MORE_LECTURE = "ADD_MORE_LECTURE"
export const ADD_CRICULUM_LECTURE = "ADD_CRICULUM_LECTURE"
export const ADD_CRICULUM_THUMNAILS = "ADD_CRICULUM_THUMNAILS"
export const DEL_CRICULUM_THUMNAIL = "DEL_CRICULUM_THUMNAIL,"
export const DEL_CRICULUM = " DEL_CRICULUM,"
export const DEL_CRICULUM_LECTURE = "DEL_CRICULUM_LECTURE,"
export const NETWORK_FAIL = "NETWORK_FAIL"


// Instructor Liveclasses 

export const ADD_LIVECLASS_INPUT = "ADD_LIVECLASS"
export const ADD_LIVECLASS_MORE = "ADD_LIVECLASS_MORE"
export const DEL_LIVECLASS = " DEL_LIVECLASS,"


// Instructor Quiz

export const ADD_QUIZ_QUESTION_INPUT = "ADD_QUIZ_QUESTION_INPUT"
export const QUIZ_OPTION_RADIO = "QUIZ_OPTION_RADIO"
export const ADD_QUIZ_OPTION_INPUT = "    ADD_QUIZ_OPTION_INPUT"
export const ADD_MORE_QUIZ = "    ADD_MORE_QUIZ,"
export const ADD_MORE_OPTION = "    ADD_MORE_OPTION,"
export const DEL_QUESTION = "    DEL_QUESTION,"
export const DEL_OPTIONS = "    DEL_OPTIONS,"


// Instructor Previews

export const ADD_LECTURE_PREVIEW = "ADD_LECTURE"
export const ADD_MORE_LECTURE_PREVIEW = "ADD_MORE_LECTURE_PREVIEW"
export const ADD_CRICULUM_THUMNAIL_PREVIEW = "ADD_CRICULUM_THUMNAIL"
export const DEL_CRICULUM_THUMNAIL_PREVIEW = "DEL_CRICULUM_THUMNAIL"
export const DEL_CRICULUM_LECTURE_PREVIEW = "DEL_CRICULUM_LECTURE"
export const NETWORK_FAIL_PREVIEW = "NETWORK_FAIL"
export const ADD_CRICULUM_LECTURE_PREVIEW = "ADD_CRICULUM_LECTURE_PREVIEW"
export const CLEAR_STATE = "CLEAR_STATE"


// Student Courses
export const GET_COURSES = "GET_COURSES"
export const GET_COURSES_SEARCH = "GET_COURSES_SEARCH"


// Page no 

export const PAGE_NO = "PAGE_NO"


// WEBSITE blogs and News 

export const GET_BLOGS = "GET_BLOGS"
export const GET_NEWS = "GET_NEWS"





// export const UPDATE_USER = 'UPDATE_USER';
// export const GET_USER = "GET_USER";
// export const GET_ONLION_USER = "GET_ONLION_USER";

// export const GET_FRIEND_REQUEST = 'GET_FRIEND_REQUEST';
// export const UPDATE_USER_SEND_REQ = 'UPDATE_USER_SEND_REQ';
// export const UPDATE_USER_CENCEL_REQ = 'UPDATE_USER_CENCEL_REQ';
// export const UNFRIEND_REQ = 'UNFRIEND_REQ';

// export const LOGIN_ERROR = "LOGIN_ERROR";
// export const LOGIN_START = 'LOGIN_START';
// export const LOGIN_FAIL = ' LOGIN_FAIL';
// export const LOGOUT = ' LOGOUT';



