export default {
  ar: {
    title: 'تطبيق الحجز',
    language: 'عربي',
    en1: 'الصفحة الرئيسية',
    en2: 'خدمات',
    en3: 'فئات',
    en4: 'القوارب',
    en5: 'أخبار',
    en6: 'اتصل بنا',
    en7: 'معلومات عنا',
    en8: 'تسجيل الدخول',
    en9: 'لوريم إيبسوم',
    en10: 'لوريم إيبسوم هو ببساطة نص شكلي يستخدم في صناعة الطباعة والتنضيد.',
    en11: 'لوريم إيبسوم هو ببساطة نص شكلي للطباعة والتنضيد',
    en12: 'احجز الآن',
    ar1: 'لوريم إيبسوم هو ببساطة نص شكلي',
    ar2: 'أفضل وجهات اليخوت في دبي',
    ar3: 'جزر النخلة جميرا',
    ar4: 'مرسى دبي',
    ar5: 'خور دبي',
    ar6: 'برج العرب',
    ar7: 'جزر العالم',
    ar8: 'لوريم إيبسوم هو ببساطة نص شكلي للطباعة والتنضيد',
    ar9: 'لوريم إيبسوم هو ببساطة نص شكلي',
    ar10: 'أعلى الخدمات',
    ar11: 'ميكانيكي',
    ar12: 'رعاية القارب / اليخوت',
    ar13: 'الكهرباء',
    ar14: 'لوريم إيبسوم هو ببساطة نص شكلي',

    al1: 'لوريم إيبسوم هو ببساطة نص شكلي',
    al2: 'شراء أو استئجار اختر القارب المفضل لديك',
    al3: 'امتلاك يخت فاخر هو حرية استكشاف العالم بشروطك بلا حدود. مع 45 عامًا من الخبرة في الحصول على أفضل اليخوت بأفضل الأسعار ، فإن فريق YPI من الوسطاء في جميع أنحاء العالم خبراء في العثور على اليخت المناسب لكل عميل.',
    al4: 'استكشاف المزيد',
    al5: 'الحماية من مرض كوفيد -19',
    al6: 'إجراءات وقائية ضد كوفيد -19',
    al7: 'امتلاك يخت فاخر هو حرية استكشاف العالم بشروطك بلا حدود. مع 45 عامًا من الخبرة في الحصول على أفضل اليخوت بأفضل الأسعار ، فإن فريق YPI من الوسطاء في جميع أنحاء العالم خبراء في العثور على اليخت المناسب لكل عميل.',
    al8: 'استكشاف المزيد',
    al9: 'نصيحة للأمام',
    al10: 'نصيحة صغيرة يمكن أن تقطع شوطا طويلا',
    al11: 'امتلاك يخت فاخر هو حرية استكشاف العالم بشروطك بلا حدود. مع 45 عامًا من الخبرة في الحصول على أفضل اليخوت بأفضل الأسعار ، فإن فريق YPI من الوسطاء في جميع أنحاء العالم خبراء في العثور على اليخت المناسب لكل عميل.',
    al12: 'استكشاف المزيد',
    al13: 'الحياة سهلة',
    al14: 'احجز خدمة تنظيف منزلية موثوقة في الإمارات في غضون 60 ثانية',
    al15: 'هناك طرق أفضل لك لقضاء وقتك ، لذلك قمنا بتسهيل الأمر عليك.',
    al16: 'احجز تنظيف منزلك في 60 ثانية ، وسيتولى متخصصونا الباقي.',
    al17: 'احجز خدمتك',
    al18: 'اختر التاريخ والوقت المفضل لديك لتنظيف منزلك في بضع خطوات واترك الباقي لنا!',
    al19: 'احصل على خدمتك',
    al20: 'اختر التاريخ والوقت المفضل لديك لتنظيف منزلك في بضع خطوات واترك الباقي لنا!',
    al21: 'استمتع',
    al22: 'اختر التاريخ والوقت المفضل لديك لتنظيف منزلك في بضع خطوات واترك الباقي لنا!',
    al23: 'خذنا معك أينما كنت',
    al24: 'احصل على تطبيق خدمة الحجز الآن!',
    al25: 'احجز مواعيدك وقم بإدارتها ببضع نقرات ، واستعرض ملفك الشخصي المهني وتقييماتك ، واطلع على الموقع في الوقت الفعلي لمهنيك المهني وغير ذلك الكثير.',

    ax1: 'خدمات رعاية القوارب / اليخوت',
    ax2: 'بحث...',

    ac1: 'غسيل القارب',
    ac2: 'تنظيف الهيكل تحت الماء',
    ac3: 'فينيل بوليش',
    ac4: 'فينيل بوليش',
    ac5: 'إزالة الصدأ',
    ac6: 'نظيفة عميق',
    ac7: 'سجاد / تنظيف داخلي',
    ac8: 'تلميع وتشميع',
    ac9: 'غرفة بيلج نظيفة',
    ac10: 'غرفة المحرك نظيفة',
    ac11: 'التطهير والتطهير',
    ac12: 'مكافحة الآفات',
    ac13: 'حزم التنظيف الشهرية',
    ac14: "أضواء",
    ac15: "تكيف",
    ac16: "مضخة بيلج",
    ac17: "مضخة مياه عذبة",
    ac18: "GPS / سونار و VHF",
    ac19: "تبديل البطارية",
    ac20: "الصدر البحر",
    ac21: "أنكوراج وينش",
    ac22: "وظائف مخصصة",
    ac23: "تصليح المراحيض",

    ac24: 'صيانة المحرك',
    ac25: 'خدمة المحرك العادية',
    ac26: 'إصلاح المحرك',
    ac27: 'الهيدروليكا ذات الصلة',
    ac28: 'المقود',
    ac29: 'صيانة مقطورة القارب',

    ac30: 'خدمات رعاية القوارب / اليخوت',
    ac31: 'الخدمات الكهربائية',
    ac32: 'خدمات ميكانيكي',


    ac33: 'غسيل القارب',
    ac34: 'Boi جيد جدًا يحب لعب الجلب والآيس كريم! لطيف مع الجميع. خائف من المطر.',
    ac35: 'السعر',
    ac36: '100 درهم إماراتي',
    ac37: 'الضرب',
    ac38: '5/5',
    ac39: 'خدمة بواسطة',
    ac40: 'ABT PVT.LTD',



    ac41: 'يخت أسود فاخر مع جاكوزي',
    ac42: 'تنظيف الهيكل تحت الماء',
    ac43: 'نوع الخدمة',
    ac44: 'الخدمة 1',
    ac45: 'مدة الخدمة بالدقائق',
    ac46: 'موقع الخدمة',
    ac47: 'أسئلة مكررة',
    ac48: 'ماذا تشمل هذه الخدمة؟',
    ac49: 'إعداد كامل لسرير التدليك المعقم',
    ac50: 'زيوت العلاج العطري عالية الجودة للتدليك',
    ac51: 'يوفر المناشف والموسيقى الهادئة للاسترخاء',
    ac52: 'شموع معطرة',
    ac53: 'الخدمة حصريا للسيدات فقط',
    ac54: 'يستخدم مقدمو الخدمة الموثوقون لدينا هذه العلامات التجارية:',

    ac55: 'نوفيل',
    ac56: 'شفهي',
    ac57: 'لا أحد',
    ac58: 'أي معلومات مهمة يحتاج مقدم الخدمة إلى معرفتها؟',
    ac59: 'للحصول على أي معلومات مهمة تتعلق بخدمتك مثل حساسية الجلد أو الحساسية أو أي مشكلة ذات صلة ، يرجى التواصل مع المزود من خلال زر الاتصال بموفر الخدمة في صفحة الطلب الخاصة بك.'
    ,
    ac60: 'ما هو العلاج بالروائح؟',
    ac61: 'يستخدم التدليك بالزيوت العطرية الزيوت الأساسية. تشمل الروائح الشعبية النعناع والخزامى والليمون والبرغموت والورد على سبيل المثال لا الحصر. يمكن أن يساعدك العلاج بالروائح على الاسترخاء وقد يساعد في النوم أيضًا.'
    ,
    ac62: 'احجز موعدًا'
  },
  en: {
    title: 'Booking App',
    language: 'EN',
    en1: 'Home',
    en2: 'Services',
    en3: 'Categories',
    en4: 'Boats',
    en5: 'News',
    en6: 'Contact Us',
    en7: 'About Us',
    en8: 'Login',
    en9: 'Lorem Ipsum',
    en10: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    en11: 'Lorem Ipsum is simply dummy text of the printing and typesetting',
    en12: 'Book Now',
    ar1: 'Lorem Ipsum is simply dummy text',
    ar2: 'Best Yacht Destinations in Dubai',
    ar3: 'The Palm Jumeirah Islands',
    ar4: 'The Dubai Marina',
    ar5: 'The Dubai Creek',
    ar6: 'The Burj Al Arab',
    ar7: 'The World Islands',
    ar8: 'Lorem Ipsum is simply dummy text of the printing and typesetting',
    ar9: 'Lorem Ipsum is simply dummy text',
    ar10: 'Top Services',
    ar11: 'Mechanic',
    ar12: 'Boat / Yacht care',
    ar13: 'Electrical',
    ar14: 'Lorem Ipsum is simply dummy text',

    al1: 'Lorem Ipsum is simply dummy text',
    al2: 'Buy or Rent Choose Your favourite Boat',
    al3: 'Owning a superyacht is the freedom to explore the world on your terms without limits. With 45 years of experience sourcing the best yachts at the best prices, YPI’s team of worldwide brokers are experts in finding the right yacht for every client.',
    al4: 'Explore more',
    al5: 'COVID-19 PROTECTION',
    al6: 'Preventive measures against COVID-19',
    al7: 'Owning a superyacht is the freedom to explore the world on your terms without limits. With 45 years of experience sourcing the best yachts at the best prices, YPI’s team of worldwide brokers are experts in finding the right yacht for every client.',
    al8: 'Explore more',
    al9: 'TIP IT FORWARD',
    al10: 'A little tip can go a long way',
    al11: 'Owning a superyacht is the freedom to explore the world on your terms without limits. With 45 years of experience sourcing the best yachts at the best prices, YPI’s team of worldwide brokers are experts in finding the right yacht for every client.',
    al12: 'Explore more',
    al13: 'LIFE MADE EASY',
    al14: 'Book a reliable home cleaning service in UAE within 60 seconds',
    al15: 'There are better ways for you to spend your time, so we made it easy for you.',
    al16: 'Book your house cleaning in 60 seconds, and our professionals will take care of the rest.',
    al17: 'Book your service',
    al18: 'Choose your preferred date and time for your home cleaning in a few steps and leave the rest to us!',
    al19: 'Get your service done',
    al20: 'Choose your preferred date and time for your home cleaning in a few steps and leave the rest to us!',
    al21: 'Have fun',
    al22: 'Choose your preferred date and time for your home cleaning in a few steps and leave the rest to us!',
    al23: 'TAKE US EVERYWHERE WITH YOU',
    al24: 'Get the Booking Service App now!',
    al25: 'Book and manage your appointments with a few taps, view your professional’s profile and ratings, see real-time location of your professional and much more.'
    ,
    ax1: 'Boat / Yacht care Services',
    ax2: 'Search...',

    ac1: 'Boat Wash',
    ac2: 'Underwater Hull Cleaning',
    ac3: 'Vinyle Polish',
    ac4: 'Vinyle Polish',
    ac5: 'Rust Removing',
    ac6: 'Deep Clean',
    ac7: 'Carpet / Interior Cleaning',
    ac8: 'Polishing and Waxing',
    ac9: 'Bilge Room Clean',
    ac10: 'Engine Room Clean',
    ac11: 'Sinitizing and Disinfection',
    ac12: 'Pest Control',
    ac13: 'Monthy Cleaning Packages',

    ac14: "Lights",
    ac15: "Air Conditioning",
    ac16: "Bilge Pump",
    ac17: "Fresh Water Pump",
    ac18: "GPS/ Sonar and VHF",
    ac19: "Battery Replacement",
    ac20: "Sea Chest",
    ac21: "Anchorage Whinch",
    ac22: "Custom Jobs",
    ac23: "Toilet Repairs",

    ac24: "Engine Maintainance",
    ac25: "Engine Regular Service",
    ac26: "Engine Overhauling",
    ac27: "Hydraulics Related",
    ac28: "Steering Wheel",
    ac29: "Boat Trailer Maintainance",

    ac30: 'Boat / Yacht care Services',
    ac31: 'Electrical Services',
    ac32: 'Mechanic Services',

    ac33: 'Boat Wash',
    ac34: 'A very good boi that loves playing fetch and ice-cream! Gentle with everyone. Scared of the rain.',
    ac35: 'Price',
    ac36: '100 AED',
    ac37: 'Ratting',
    ac38: '5/5',
    ac39: 'Service By',
    ac40: 'ABT PVT.LTD',


    ac41: 'Black Luxury Yacht with Jacuzzi',
    ac42: 'Underwater Hull Cleaning',
    ac43: 'Service Type',
    ac44: 'Service 1',
    ac45: 'Service Duration in Minutes',
    ac46: 'Service Location',
    ac47: 'Frequently Asked Questions',
    ac48: 'What does this service include?',
    ac49: 'A full setup of sanitized massage bed',
    ac50: 'Quality aromatherapy oils for the massage',
    ac51: 'Provides Towels and relaxing soft music',
    ac52: 'Scented candles',
    ac53: 'Service is exclusively for womens only',
    ac54: 'Our trusted service providers use these brands:',
    ac55: 'Novell',
    ac56: 'Orial',
    ac57: 'Nashi',
    ac58: 'Any important information that the provider needs to know?',
    ac59: 'For any important info related to your service such as skin sensitivities, allergies, or any related issue, please reach out to provider through Contact Provider button on your order page.',

    ac60: 'What is an Aromatherapy Spa treatment?',
    ac61: 'An aromatherapy massage uses essential oils. Popular scents include peppermint, lavender, lemon, bergamot, and rose to name a few. Aromatherapy can help you relax and it may help with sleep, too.',
    ac62: 'Book an Appointment',
  },
};
